---
title: "backend-calculator"
author: "Beck Addison"
date: "11/2/2019"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import-data-packages}
library(tidyverse)
library(shiny)
library(readxl)
library(knitr)

```

---

```{r test_tibble}

numsamples = 2000

regions = sample(c("Midwest","South","Northeast", "West"), numsamples, replace = T)

monthly_bill = sample(1000, size = numsamples, replace = T)

salary = sample(100000, size = numsamples, replace = T)

price_elec = sample(0.50, size = numsamples, replace = T)

housingtype = sample(c("Single-Family Detached", "Apartment 2-4", "Apartment 5 or more", "Mobile", "Single-Family Attached"), numsamples, replace = T)

climate = sample(c("Very Cold","Mixed-humid","Mixed-dry","Hot-humid","Marine"), numsamples, replace = T)

ownership = sample(c("Rented","Owned"), numsamples, replace = T)

heating_fuel = sample(c("gas","electric"), numsamples, replace = T)

test_tibble = tibble(regions, salary, monthly_bill, price_elec, housingtype, climate, ownership, heating_fuel)

test_tibble <- test_tibble %>%
  mutate(currEn = monthly_bill/price_elec)


```

```{r calculators}
environ_calc <- function(region, subregion, urban, climate, housingtype, sqft, rent, yearcst, hshld, income, included_in_rent, heating_fuel){}

calc_pricept <- function(gas_items, elec_items) {
  return(3412.142*(0.20*gas_items+0.15*elec_items)/2)
}

fin_calc <- function(userSalary, currEn, pricePt, year) {
  
  pointarr = c()
  i = 0
  
  while(year <= 2050){
    
    point = userSalary - (pricePt*currEn)*0.15*year/10 
    
    pointarr[i] <- point
    
    pricePt = pricePt*0.15*year/10
    i = i + 1
  }
  return(pointarr)
}

gas_elec_calc <- function(what_car, what_heater, what_lighting) {
    gas_items = 0
    elec_items = 0
    gasoline_car = FALSE
    
    if(what_car == "Gasoline") {
      gas_items = gas_items + 2
    } else if(what_car == "Hybrid") {
      gas_items = gas_items + 0.5
      elec_items = elec_items + 0.5
    }
    
    if(what_heater == "Electric") {
      elec_items = elec_items + 1
    } else if(what_heater == "Gas") {
      gas_items = gas_items + 1
    } else {
      elec_items = elec_items + 0.5
    }
    
    if(what_lighting == "Incadescent") {
      elec_items = elec_items + 1
    } else {
      elec_items = elec_items + 0.5
    }
    
    return (c(gas_items, elec_items))
}

```

You can also embed plots, for example:

```{r shiny-io, echo=TRUE}

ui <- fluidPage(
  titlePanel("Test Page"),
  sidebarLayout(
    sidebarPanel(
      numericInput("salary", 
                   
                   label = "What is your annual estimated salary?",
                   value = 50000,
                   min = 10000,
                   max = 900000,
                   step = 5000),
      numericInput("current_bill",
                   label = "What is your current energy bill?",
                   value = 100,
                   min = 0,
                   max = 1000),
  
      selectInput("want_to_spend", 
                   
                  label = "What percentage of your income
                   do you see yourself comfortably spending?", 
                   
                  choices = c(
                     "5 percent",
                     "10 percent",
                     "15 percent",
                     "25 percent",
                     "I'm all in! (up to 75 percent)"
                     )
                   ),
      
      selectInput("what_region", 
                  label = "In what region of the U.S. do you currently
                  live?",
                  choices = c("Northeast","Midwest","South","West")
                  ),
      
      selectInput("what_car",
                  label = "Do you have a car? If so, gasoline, electric
                  or hybrid",
                  choices = c(
                    "No car", "Gasoline", "Electric","Hybrid")),
      
      selectInput("what_heater",
                  label = "Do you have an electric water heater, or gas?",
                  choices = c("Electric", "Gas","Hybrid Electric")),
      
      selectInput("what_lighting",
                  label = "What kind of lights do you have, for the most   part?",
                  choices = c("Incandescent","LED")),
                  ),
    
  mainPanel(
    plotOutput("finance_plot"),
    textOutput("info"),
    tags$a(
      href = "https://www.eia.gov/consumption/residential/index.php",
      "Source: EIA",
      target = "_blank"
      )
    )
  )
)

server <- function(input, output) {

  # output$finance_plot <- reactivePlot({
  #   
  #   items <- reactive(
  #     gas_elec_calc(reactive(input$what_car),
  #                   reactive(input$what_heater),
  #                   reactive(input$what_lighting)
  #                   )
  #     )
  #   
  #   pricePt = reactive(calc_pricept(items[1], items[2]))
  #   
  #   currEn = reactive(reactive(pricePt)*reactive(input$current_bill))
  #   yeararr <- c(2010:2050)
  #   
  #   pointarr <- reactive(
  #     fin_calc(reactive(input$userSalary),
  #              currEn,
  #              pricePt,
  #              yeararr[1])
  #   )
  #   
  #   tibble2 = tibble(yeararr, pointarr)
  #   
  #   ggplot(tibble2, aes(yeararr, pointarr)) +
  #     geom_point()

  output$finance_plot <- renderPlot({
    test_tibble %>%
    filter(regions == input$what_region,
           salary >= input$salary - 5000 || salary <= input$salary + 5000) %>%
    ggplot(aes(x = heating_fuel, y = monthly_bill, fill = ownership)) +
      geom_bar(stat = "identity")
  })
}


shinyApp(ui, server)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
